channels:
- conda-forge
dependencies:
- click
- furo
- numpy >=1.15.0
- platformdirs
- pre-commit
- prettytable
- python >=3.10
- pyyaml
- setuptools_scm
- sphinx
- sphinx-argparse
- termcolor
- tqdm
